CREATE DATABASE NovaInventoryJeffreyBD;
GO

USE NovaInventoryJeffreyBD;
GO

-- TABLA DE ESTADOS DE CLIENTES (ACTIVO, INACTIVO, BLOQUEADO)
CREATE TABLE EstadoCliente(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(30) NOT NULL
);
GO

-- TABLA DE ESTADOS DE PRODUCTOS (DISPONIBLE, AGOTADO)
CREATE TABLE EstadoProducto(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(30) NOT NULL
);
GO

-- TABLA DE CLIENTES
CREATE TABLE Cliente(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(100) NOT NULL,
	Apellido VARCHAR(100) NOT NULL, 
	Telefono VARCHAR(25) NOT NULL,
	Correo VARCHAR(100) NOT NULL, 
	Pass VARCHAR(MAX) NOT NULL,
	IdEstadoCliente INT NOT NULL FOREIGN KEY REFERENCES EstadoCliente(Id)
);
GO

-- TABLA DE PRODUCTOS
CREATE TABLE Producto(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(100) NOT NULL,
	Descripcion VARCHAR(MAX) NOT NULL,
	Precio DECIMAL(10,2) NOT NULL, -- Usamos DECIMAL para el manejo correcto de los precios
	Cantidad INT NOT NULL,
	IdEstadoProducto INT NOT NULL FOREIGN KEY REFERENCES EstadoProducto(Id)
);
GO